### ISSUE TITLE
Unable to delete account account created with this package.

### ISSUE THREAD

**Issue by YehudaBialik** [gregneagle/pycreateuserpkg#35] opened 2019-06-06 18:40 UTC
I'm trying to delete the account I created using this package, but I keep getting an error message.

I created the package using:
`python createuserpkg --name=ladmin18 --uid=898 --password=XXXX --version=201809041105 --identifier=lan.bialik.create_ladmin18.pkg /Users/xadmin/Desktop/create_ladmin18.pkg`
and installed it using munki.  When I try to delete it, using munki nopkg postinstall script:
`/usr/bin/dscl localhost delete /Local/Default/Users/ladmin18`
the account isn't deleting.

When I run that command in terminal I get the following error message:
```
<main> delete status: eDSPermissionError
<dscl_cmd> DS Error: -14120 (eDSPermissionError)
```
As usual, I'm sure this has nothing to do with you script, but just in case...

Yehuda

**Comment by gregneagle** [comment] 2019-06-07 02:00
Same result with `/usr/bin/dscl . delete /Users/ladmin18`?

And have you tested using `dscl` to delete user accounts created some other way (like manually)?

**Comment by gregneagle** [comment] 2019-06-07 02:04
FWIW `sudo dscl localhost delete /Local/Default/Users/somename` works here to remove an account that was created/installed with a pycreateuserpkg package...

**Comment by gregneagle** [comment] 2019-06-07 02:17
Tested your scenario literally:
```
bash-3.2$ python createuserpkg --name=ladmin18 --uid=898 --password=XXXX --version=201809041105 --identifier=lan.bialik.create_ladmin18.pkg create_ladmin18.pkg
pkgbuild: Inferring bundle components from contents of /var/folders/tc/sd4_mtvj14jdy7cg21m2gmcw000495/T/tmpOnrCEG/create_user
pkgbuild: Adding top-level postinstall script
pkgbuild: Wrote package to create_ladmin18.pkg
bash-3.2$ sudo installer -pkg create_ladmin18.pkg -target /
installer: Package name is create_ladmin18
installer: Installing at base path /
installer: The install was successful.
bash-3.2$ sudo /usr/bin/dscl localhost delete /Local/Default/Users/ladmin18
bash-3.2$ sudo /usr/bin/dscl localhost read /Local/Default/Users/ladmin18
<dscl_cmd> DS Error: -14136 (eDSRecordNotFound)
```

**Comment by YehudaBialik** [comment] 2019-06-07 09:38
Strange.

Okay, thanks for your help and patience.

Yehuda

**Comment by jelockwood** [comment] 2019-06-07 10:39
@gregneagle 
@YehudaBialik 
I re-read this issue. I maybe wrong but I am thinking @YehudaBialik is misunderstanding what Munki can do.

The package has been created, the package has been added to Munki and via Munki it has been successfully installed on the client Mac. As I read it @YehudaBialik is then saying he told Munki to uninstall this package and he expected this would 'uninstall' the user account that had been created.

As Greg will of course know this is effectively a payload free package in that it has no files as a payload to install it is merely running a script.

I don't believe this would be possible, it would at best remove the receipt and that is it. I don't believe it would ever remove the user account. The user account is not a file installed by the installer package after all. Apple installer packages _do not_ have matching uninstall scripts in them. In the cases developers provide uninstallers these are in effect 'installers' which run scripts which then laboriously delete things.

Munki is however able to uninstall _files_ because it looks at the matching BOM and receipts entries to see the list of files that was installed.

In this case we are not installing a file we are creating a user account and hence I do not see this being possible.

Just saying… ;-)

What would be possible to do is to add an uninstall script in Munki to run a corresponding dscl delete command. This would be added to the pkginfo for the - in this case create_ladmin.pkg

**Comment by gregneagle** [comment] 2019-11-03 17:34
Closing this old unreproducible issue.

**Closed as completed by gregneagle** 2019-11-03 17:34 UTC
